<?php require 'templates/layout/header.phtml' ?>

<a href="agregar/" type="button" class='btn btn-secondary btn-sm ml-auto'>Ingresar nuevo modelo</a>

<div class="p-3 mb-2" >
<h5 class="titulo2">Listado de modelos en stock:</h5>
</div>
<div class="d-flex justify-content-center ">
<ul class="list-group">
<?php foreach($modelos as $modelo): ?>
    <li class="list-group-item item-modelo ">
        <div class="label"> 
        <a href="verDetalle/<?= $modelo->id_modelo ?>"><b><?= $modelo->nombre_modelo ?></b> : $ <?=substr($modelo->precio,0,25)?> , Talle <?= $modelo->talle ?> , Material : <?= $modelo->material?>
        </div>
        <div class="actions">
            <a href="modificar/<?= $modelo->id_modelo ?>" type="button" class='btn btn-warning btn-sm ml-auto'>Modificar</a> 
            <a href="eliminar/<?= $modelo->id_modelo ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Eliminar modelo</a>
        </div>
    </li>
<?php endforeach ?>
</ul>
</div>

<p class="mt-3"><small>Mostrando <?=$count?> modelos de zapatillas</small></p>


<?php require 'templates/layout/footer.phtml' ?>
